<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeShowConsole Condition="'$(RuntimeShowConsole)' == ''">false</RuntimeShowConsole>
    <RuntimeDiagnostics Condition="'$(RuntimeDiagnostics)' == ''">false</RuntimeDiagnostics>
    <OutputType Condition="'$(RuntimeShowConsole)' == 'true'">Exe</OutputType>
    <OutputType Condition="'$(RuntimeShowConsole)' != 'true'">WinExe</OutputType>

    <!-- Single File Settings -->
    <PublishSingleFile Condition="'$(PublishSingleFile)' == ''">true</PublishSingleFile>
    <SelfContained Condition="'$(SelfContained)' == ''">true</SelfContained>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeShowConsole)' == 'true'">
    <DefineConstants>$(DefineConstants);VERITY_RUNTIME_CONSOLE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeDiagnostics)' == 'true'">
    <DefineConstants>$(DefineConstants);VERITY_RUNTIME_DIAGNOSTICS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Verity.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\Verity.Core\Verity.Core.csproj" />
    <ProjectReference Include="..\Engine\Verity.Graphics\Verity.Graphics.csproj" />
    <ProjectReference Include="..\Engine\Verity.Input\Verity.Input.csproj" />
    <PackageReference Include="sdl2_mixer.nuget.redist" Version="2.8.1" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(Pkgsdl2_mixer_nuget_redist)\build\native\bin\x64\SDL2_mixer.dll"
             Condition="Exists('$(Pkgsdl2_mixer_nuget_redist)\build\native\bin\x64\SDL2_mixer.dll')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <Link>SDL2_mixer.dll</Link>
    </Content>
  </ItemGroup>

  <!-- Include data as resources when publishing -->
  <ItemGroup>
    <EmbeddedResource Include="scene.json" Condition="Exists('scene.json')" />
    <EmbeddedResource Include="BuildSettings.json" Condition="Exists('BuildSettings.json')" />
    <EmbeddedResource Include="UserScripts.dll" Condition="Exists('UserScripts.dll')" />
    <EmbeddedResource Include="Assets\**\*" Exclude="Assets\bin\**;Assets\obj\**" Condition="Exists('Assets')" />
  </ItemGroup>
</Project>
