<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <!-- Single File Settings -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\Verity.Core\Verity.Core.csproj" />
    <ProjectReference Include="..\Engine\Verity.Graphics\Verity.Graphics.csproj" />
    <ProjectReference Include="..\Engine\Verity.Input\Verity.Input.csproj" />
  </ItemGroup>

  <!-- Include data as resources when publishing -->
  <ItemGroup>
    <EmbeddedResource Include="scene.json" Condition="Exists('scene.json')" />
    <EmbeddedResource Include="BuildSettings.json" Condition="Exists('BuildSettings.json')" />
    <EmbeddedResource Include="UserScripts.dll" Condition="Exists('UserScripts.dll')" />
    <EmbeddedResource Include="Assets\**\*" Exclude="Assets\bin\**;Assets\obj\**" Condition="Exists('Assets')" />
  </ItemGroup>
</Project>
