<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Verity.Core\Verity.Core.csproj" />
    <ProjectReference Include="..\..\Verity.Game\Verity.Game.csproj" />
    <ProjectReference Include="..\Verity.Graphics\Verity.Graphics.csproj" />
    <ProjectReference Include="..\Verity.Input\Verity.Input.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="TestResources\scene.json" LogicalName="Verity.Tests.scene.json" />
    <EmbeddedResource Include="TestResources\Assets\BuildSettings.json" LogicalName="Verity.Tests.BuildSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ParticleTests.cs" />
    <Compile Remove="SaveManagerTests.cs" />
  </ItemGroup>

</Project>
