namespace Verity.Input;

public enum KeyCode
{
    Unknown = 0,

    A = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_A,
    B = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_B,
    C = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_C,
    D = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_D,
    E = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_E,
    F = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_F,
    G = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_G,
    H = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_H,
    I = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_I,
    J = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_J,
    K = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_K,
    L = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_L,
    M = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_M,
    N = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_N,
    O = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_O,
    P = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_P,
    Q = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_Q,
    R = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_R,
    S = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_S,
    T = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_T,
    U = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_U,
    V = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_V,
    W = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_W,
    X = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_X,
    Y = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_Y,
    Z = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_Z,

    Alpha0 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_0,
    Alpha1 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_1,
    Alpha2 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_2,
    Alpha3 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_3,
    Alpha4 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_4,
    Alpha5 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_5,
    Alpha6 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_6,
    Alpha7 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_7,
    Alpha8 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_8,
    Alpha9 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_9,

    F1 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_F1,
    F2 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_F2,
    F3 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_F3,
    F4 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_F4,
    F5 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_F5,
    F6 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_F6,
    F7 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_F7,
    F8 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_F8,
    F9 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_F9,
    F10 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_F10,
    F11 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_F11,
    F12 = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_F12,

    Space = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_SPACE,
    Return = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_RETURN,
    Escape = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_ESCAPE,
    Backspace = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_BACKSPACE,
    Tab = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_TAB,
    Delete = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_DELETE,

    Up = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_UP,
    Down = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_DOWN,
    Left = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_LEFT,
    Right = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_RIGHT,

    LeftShift = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_LSHIFT,
    RightShift = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_RSHIFT,
    LeftCtrl = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_LCTRL,
    RightCtrl = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_RCTRL,
    LeftAlt = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_LALT,
    RightAlt = SDL2.SDL.SDL_Scancode.SDL_SCANCODE_RALT,

    // Mouse Buttons (Unified)
    MouseLeft = 1001,
    MouseRight = 1002,
    MouseMiddle = 1003,
    MouseX1 = 1004,
    MouseX2 = 1005,
    }
