<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Verity.Core\Verity.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Irodori" Version="0.0.8" />
    <PackageReference Include="Irodori.Backend.OpenGL" Version="0.0.8" />
    <PackageReference Include="ppy.SDL2-CS" Version="1.0.82" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>
</Project>
