using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Linq;
using Verity.Core.ECS;

namespace Verity.Editor;

internal static class LuaLanguageServerSupport
{
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true };

    public static void EnsureProjectSupport(string? projectPath, IEnumerable<Type>? componentTypes)
    {
        if (string.IsNullOrWhiteSpace(projectPath))
            return;

        string normalizedProjectPath = Path.GetFullPath(projectPath);
        string supportRoot = Path.Combine(normalizedProjectPath, ".verity", "lua");
        string vscodeRoot = Path.Combine(normalizedProjectPath, ".vscode");

        Directory.CreateDirectory(supportRoot);
        Directory.CreateDirectory(vscodeRoot);

        File.WriteAllText(Path.Combine(supportRoot, "verity_api.lua"), BuildApiStub(componentTypes));
        File.WriteAllText(Path.Combine(vscodeRoot, "verity-lua.code-snippets"), BuildWorkspaceSnippets());
        WriteLuaRc(normalizedProjectPath);
    }

    private static void WriteLuaRc(string projectPath)
    {
        string luaRcPath = Path.Combine(projectPath, ".luarc.json");
        JsonObject root = File.Exists(luaRcPath)
            ? JsonNode.Parse(File.ReadAllText(luaRcPath)) as JsonObject ?? []
            : [];

        root["$schema"] = "https://raw.githubusercontent.com/LuaLS/vscode-lua/master/setting/schema.json";

        JsonObject workspace = EnsureObject(root, "workspace");
        EnsureStringArrayContains(workspace, "library", ".verity/lua");
        workspace["checkThirdParty"] = false;

        JsonObject runtime = EnsureObject(root, "runtime");
        runtime["version"] = "Lua 5.4";

        JsonObject completion = EnsureObject(root, "completion");
        completion["keywordSnippet"] = "Replace";

        JsonObject diagnostics = EnsureObject(root, "diagnostics");
        foreach (string global in new[] { "self", "Owner", "Time", "Input", "Keys", "Entity", "Vector2", "Vector3", "Wait", "WaitForSeconds", "WaitForTicks", "WaitForPhysicalTicks", "WaitUntil", "WaitWhile" })
            EnsureStringArrayContains(diagnostics, "globals", global);

        File.WriteAllText(luaRcPath, root.ToJsonString(JsonOptions));
    }

    private static JsonObject EnsureObject(JsonObject root, string name)
    {
        if (root[name] is JsonObject obj)
            return obj;

        obj = [];
        root[name] = obj;
        return obj;
    }

    private static void EnsureStringArrayContains(JsonObject root, string name, string value)
    {
        JsonArray array;
        if (root[name] is JsonArray existing)
        {
            array = existing;
        }
        else
        {
            array = [];
            root[name] = array;
        }

        if (!array.Any(node => string.Equals((string?)node, value, StringComparison.OrdinalIgnoreCase)))
            array.Add(value);
    }

    private static string BuildWorkspaceSnippets()
    {
        JsonObject root = new()
        {
            ["Verity Lua Behaviour"] = new JsonObject
            {
                ["prefix"] = "verity",
                ["body"] = new JsonArray
                {
                    "function Awake()",
                    "    $0",
                    "end",
                    "",
                    "function Start()",
                    "end",
                    "",
                    "function Update(deltaTime)",
                    "end"
                },
                ["description"] = "Verity Lua behaviour template"
            },
            ["Verity Coroutine"] = new JsonObject
            {
                ["prefix"] = "vcoroutine",
                ["body"] = new JsonArray
                {
                    "function ${1:RoutineName}()",
                    "    while true do",
                    "        ${2:-- body}",
                    "        coroutine.yield(Wait(${3:0.1}))",
                    "    end",
                    "end"
                },
                ["description"] = "Verity Lua coroutine template"
            }
        };

        return root.ToJsonString(JsonOptions);
    }

    private static string BuildApiStub(IEnumerable<Type>? componentTypes)
    {
        StringBuilder sb = new();
        sb.AppendLine("---@meta");
        sb.AppendLine("-- Generated by Verity. Changes may be overwritten.");
        sb.AppendLine();
        AppendClass(sb, "VerityVector2", new[] { ("X", "number"), ("Y", "number") });
        sb.AppendLine("---@param x number?");
        sb.AppendLine("---@param y number?");
        sb.AppendLine("---@return VerityVector2");
        sb.AppendLine("function Vector2(x, y) end");
        sb.AppendLine();

        AppendClass(sb, "VerityVector3", new[] { ("X", "number"), ("Y", "number"), ("Z", "number") });
        sb.AppendLine("---@param x number?");
        sb.AppendLine("---@param y number?");
        sb.AppendLine("---@param z number?");
        sb.AppendLine("---@return VerityVector3");
        sb.AppendLine("function Vector3(x, y, z) end");
        sb.AppendLine();

        AppendClass(sb, "VerityTransform", new[] { ("Position", "VerityVector2"), ("Rotation", "number"), ("Scale", "VerityVector2") });
        AppendClass(sb, "VerityComponentProxy");
        sb.AppendLine("---@param memberName string");
        sb.AppendLine("---@return any");
        sb.AppendLine("function VerityComponentProxy:GetMember(memberName) end");
        sb.AppendLine("---@param memberName string");
        sb.AppendLine("---@param value any");
        sb.AppendLine("---@return boolean");
        sb.AppendLine("function VerityComponentProxy:SetMember(memberName, value) end");
        sb.AppendLine();

        AppendComponentAlias(sb, componentTypes);

        AppendClass(sb, "VerityEntity", new[] { ("Name", "string"), ("Tag", "string"), ("Active", "boolean"), ("Transform", "VerityTransform") });
        sb.AppendLine("---@param componentTypeName VerityComponentType|string");
        sb.AppendLine("---@return boolean");
        sb.AppendLine("function VerityEntity:HasComponent(componentTypeName) end");
        sb.AppendLine("---@param componentTypeName VerityComponentType|string");
        sb.AppendLine("---@return VerityComponentProxy|nil");
        sb.AppendLine("function VerityEntity:GetComponent(componentTypeName) end");
        sb.AppendLine("---@param componentTypeName VerityComponentType|string");
        sb.AppendLine("---@param memberName string");
        sb.AppendLine("---@return any");
        sb.AppendLine("function VerityEntity:GetField(componentTypeName, memberName) end");
        sb.AppendLine("---@param componentTypeName VerityComponentType|string");
        sb.AppendLine("---@param memberName string");
        sb.AppendLine("---@param value any");
        sb.AppendLine("---@return boolean");
        sb.AppendLine("function VerityEntity:SetField(componentTypeName, memberName, value) end");
        sb.AppendLine("---@param componentTypeName VerityComponentType|string");
        sb.AppendLine("---@param methodName string");
        sb.AppendLine("---@return any");
        sb.AppendLine("function VerityEntity:Invoke(componentTypeName, methodName) end");
        sb.AppendLine();

        AppendClass(sb, "VerityScriptContext", new[] { ("Owner", "VerityEntity") });
        sb.AppendLine("---@param fn fun(...):any");
        sb.AppendLine("---@return boolean");
        sb.AppendLine("function VerityScriptContext:StartCoroutine(fn) end");
        sb.AppendLine("---@param functionName string");
        sb.AppendLine("---@return boolean");
        sb.AppendLine("function VerityScriptContext:StartCoroutineByName(functionName) end");
        sb.AppendLine("function VerityScriptContext:StopAllCoroutines() end");
        sb.AppendLine();

        AppendClass(sb, "VerityTime", new[] { ("DeltaTime", "number"), ("TotalTime", "number"), ("LogicTickCount", "integer"), ("PhysicsTickCount", "integer") });
        AppendClass(sb, "VerityInput");
        sb.AppendLine("---@param key integer|string");
        sb.AppendLine("---@return boolean");
        sb.AppendLine("function VerityInput:IsKeyDown(key) end");
        sb.AppendLine("---@param key integer|string");
        sb.AppendLine("---@return boolean");
        sb.AppendLine("function VerityInput:IsKeyPressed(key) end");
        sb.AppendLine("---@param key integer|string");
        sb.AppendLine("---@return boolean");
        sb.AppendLine("function VerityInput:IsKeyReleased(key) end");
        sb.AppendLine();

        AppendKeysClass(sb);

        AppendClass(sb, "VerityEntityApi");
        sb.AppendLine("---@param name string");
        sb.AppendLine("---@return VerityEntity|nil");
        sb.AppendLine("function VerityEntityApi:Find(name) end");
        sb.AppendLine("---@param tag string");
        sb.AppendLine("---@return VerityEntity|nil");
        sb.AppendLine("function VerityEntityApi:FindWithTag(tag) end");
        sb.AppendLine();

        sb.AppendLine("---@type VerityScriptContext");
        sb.AppendLine("self = nil");
        sb.AppendLine("---@type VerityEntity");
        sb.AppendLine("Owner = nil");
        sb.AppendLine("---@type VerityTime");
        sb.AppendLine("Time = nil");
        sb.AppendLine("---@type VerityInput");
        sb.AppendLine("Input = nil");
        sb.AppendLine("---@type VerityKeys");
        sb.AppendLine("Keys = nil");
        sb.AppendLine("---@type VerityEntityApi");
        sb.AppendLine("Entity = nil");
        sb.AppendLine();

        sb.AppendLine("---@param seconds number");
        sb.AppendLine("---@return any");
        sb.AppendLine("function Wait(seconds) end");
        sb.AppendLine("---@param seconds number");
        sb.AppendLine("---@return any");
        sb.AppendLine("function WaitForSeconds(seconds) end");
        sb.AppendLine("---@param ticks integer");
        sb.AppendLine("---@return any");
        sb.AppendLine("function WaitForTicks(ticks) end");
        sb.AppendLine("---@param ticks integer");
        sb.AppendLine("---@return any");
        sb.AppendLine("function WaitForPhysicalTicks(ticks) end");
        sb.AppendLine("---@param predicate fun():boolean");
        sb.AppendLine("---@return any");
        sb.AppendLine("function WaitUntil(predicate) end");
        sb.AppendLine("---@param predicate fun():boolean");
        sb.AppendLine("---@return any");
        sb.AppendLine("function WaitWhile(predicate) end");
        return sb.ToString();
    }

    private static void AppendClass(StringBuilder sb, string name, IEnumerable<(string Name, string Type)>? fields = null)
    {
        sb.AppendLine($"---@class {name}");
        if (fields != null)
        {
            foreach (var (fieldName, fieldType) in fields)
                sb.AppendLine($"---@field {fieldName} {fieldType}");
        }
        sb.AppendLine($"local {name} = {{}}");
    }

    private static void AppendComponentAlias(StringBuilder sb, IEnumerable<Type>? componentTypes)
    {
        var names = (componentTypes ?? Enumerable.Empty<Type>())
            .Where(static type => typeof(Component).IsAssignableFrom(type) && !type.IsAbstract)
            .SelectMany(static type => new[] { type.Name, type.FullName })
            .Where(static name => !string.IsNullOrWhiteSpace(name))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(static name => name, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        if (names.Length == 0)
        {
            sb.AppendLine("---@alias VerityComponentType string");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("---@alias VerityComponentType");
        for (int i = 0; i < names.Length; i++)
            sb.AppendLine($"---| \"{EscapeLuaString(names[i]!)}\"");
        sb.AppendLine();
    }

    private static void AppendKeysClass(StringBuilder sb)
    {
        sb.AppendLine("---@class VerityKeys");
        foreach (string name in Enum.GetNames(typeof(Verity.Input.KeyCode)))
            sb.AppendLine($"---@field {name} integer");
        sb.AppendLine("local VerityKeys = {}");
        sb.AppendLine();
    }

    private static string EscapeLuaString(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
