<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Engine\Verity.Core\Verity.Core.csproj" />
    <ProjectReference Include="..\..\Engine\Verity.Graphics\Verity.Graphics.csproj" />
    <ProjectReference Include="..\..\Engine\Verity.Input\Verity.Input.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Locales\*.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EditorResources\**\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
    <PackageReference Include="Hexa.NET.ImGui.Backends" Version="1.0.18" />
    <PackageReference Include="Hexa.NET.ImGui.Backends.SDL2" Version="1.0.18" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
  </ItemGroup>
</Project>
